name: melon-ticket-checker
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  check-tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 204755
          schedule-id: 100001
          seat-id: 10000101
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '티켓이 판매 중입니다!'
